langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      model-name: gpt-4o-mini
      temperature: 1.2
      timeout: PT60S
      log-requests: true
      log-responses: true
logging:
  level.dev:
    langchain4j: DEBUG
    ai4j.openai4j: DEBUG
